In [6]:
def right_rotate(d,k):
    res = []
    res.extend(d[-k:])
    res.extend(d[:len(d)-k])
    print(res)

a = [7,4,6,9,10,14]    

right_rotate(a,2)



# [7,4,6,9,10,14] RR by 2 => [10,14,7,4,6,9,10]


[10, 14, 7, 4, 6, 9]


In [ ]:
#### 
1) concatenate
2) np.dot(), np.matmul()
3) np.multiply()
4) a.T
5) 

In [2]:
import numpy as np

## 1) Operations on Array/Matrix

### Array operations

In [3]:
r1 =[[12,13,4],[15,16,17],[18,19,20],[21,22,24]]
a1 = np.array(r1)
a1

array([[12, 13,  4],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 24]])

#### Adding scalar value to each and every array value

In [5]:
a1+20

array([[32, 33, 24],
       [35, 36, 37],
       [38, 39, 40],
       [41, 42, 44]])

In [8]:
a1

array([[12, 13,  4],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 24]])

#### Row wise addition

In [10]:
a1+[[10],[15],[20],[25]]

array([[22, 23, 14],
       [30, 31, 32],
       [38, 39, 40],
       [46, 47, 49]])

In [12]:
a2 = a1+[[10],[15],[20],[25]]
a2

array([[22, 23, 14],
       [30, 31, 32],
       [38, 39, 40],
       [46, 47, 49]])

In [13]:
a1

array([[12, 13,  4],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 24]])

#### Column wise addition

In [15]:
a1+[10,15,20]

array([[22, 28, 24],
       [25, 31, 37],
       [28, 34, 40],
       [31, 37, 44]])

In [18]:
print(a1)
print(a1.shape)

[[12 13  4]
 [15 16 17]
 [18 19 20]
 [21 22 24]]
(4, 3)


#### Adding array of same dimension

In [20]:
a1+[[2,3,4],
    [1,4,3],
    [2,1,3],
    [1,2,4]]

array([[14, 16,  8],
       [16, 20, 20],
       [20, 20, 23],
       [22, 24, 28]])

In [21]:
a1

array([[12, 13,  4],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 24]])

## 2) Numpy array functions

### a) np.sum()

In [22]:
a1

array([[12, 13,  4],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 24]])

In [24]:
12+13+4+15+16+17+18+19+20+21+22+24

201

In [25]:
a1.sum()

201

In [26]:
a1

array([[12, 13,  4],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 24]])

In [28]:
# Row wise addition, axis=1
a1.sum(axis=1)

array([29, 48, 57, 67])

In [30]:
# Column wise addition, axis=0
a1.sum(axis=0)

array([66, 70, 65])

### b) np.max() and np.min()

In [31]:
a1

array([[12, 13,  4],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 24]])

In [33]:
print(np.max(a1))
print(np.min(a1))

24
4


#### c) np.argmax() and np.argmin()
<b>np.argmax()</b> - Returns the indices of the maximum values along an axis <br>  
<b>np.argmin() </b>- Returns the indices of the minimum values along an axis 

In [34]:
p1 = np.array([12,14,7,79,32,45,28,4,17])
p1

array([12, 14,  7, 79, 32, 45, 28,  4, 17])

In [36]:
print(np.max(p1))
print(np.min(p1))
p1[3]

79
4


79

In [37]:
print(np.argmax(p1))
print(np.argmin(p1))

3
7


In [39]:
max_value = p1[np.argmax(p1)]
min_value = p1[np.argmin(p1)]
print('Max_value is ',max_value)
print('Min_value is ',min_value)

Max_value is  79
Min_value is  4


In [40]:
r2 = [[16,15,21],[15,16,8],[19,2,18],[9,12,13]]
p2 = np.array(r2)
print(p2)

[[16 15 21]
 [15 16  8]
 [19  2 18]
 [ 9 12 13]]


In [41]:
print(np.argmax(p2,axis=0))  # column wise
print(np.argmin(p2,axis=0))  # column wise
print(np.argmax(p2,axis=1))  # row wise
print(np.argmin(p2,axis=1))  # row wise

[2 1 0]
[3 2 1]
[2 1 0 2]
[1 2 1 0]


### d) np.sort

In [42]:
r1 = np.array([34,23,56,12,39])
print(r1)          

[34 23 56 12 39]


In [43]:
r2 = np.sort(r1) # ascending order
print(r2)

[12 23 34 39 56]


In [46]:
r2[::-1]

array([56, 39, 34, 23, 12])

In [47]:
r3 = np.array([[11,21,18],[24,35,16],[7,14,3]])
print(r3)

[[11 21 18]
 [24 35 16]
 [ 7 14  3]]


In [48]:
# sorts row wise
r4 = np.sort(r3,axis=1)
print(r4)

[[11 18 21]
 [16 24 35]
 [ 3  7 14]]


In [49]:
r3

array([[11, 21, 18],
       [24, 35, 16],
       [ 7, 14,  3]])

In [51]:
# sorts column wise
r4 = np.sort(r3,axis=0)
print(r4)

[[ 7 14  3]
 [11 21 16]
 [24 35 18]]


In [52]:
r3

array([[11, 21, 18],
       [24, 35, 16],
       [ 7, 14,  3]])

#### e) np.where() - returns index position for the matching conditions

In [53]:
p1

array([12, 14,  7, 79, 32, 45, 28,  4, 17])

In [38]:
n2 = np.where(p1%3==0)
print(n2)

(array([0, 5], dtype=int64),)


In [55]:
p1[np.where(p1%3==0)]

array([12, 45])

In [56]:
p1

array([12, 14,  7, 79, 32, 45, 28,  4, 17])

In [57]:
np.where(p1 < 20)

(array([0, 1, 2, 7, 8], dtype=int64),)

In [58]:
p1[np.where(p1 < 20)]

array([12, 14,  7,  4, 17])

In [61]:
p1

array([12, 14,  7, 79, 32, 45, 28,  4, 17])

In [62]:
t1 = np.where(p1 < 20, p1+5, p1*2)
print(t1)

[ 17  19  12 158  64  90  56   9  22]


In [64]:
p1

array([12, 14,  7, 79, 32, 45, 28,  4, 17])

In [66]:
np.where(p1%2==0, p1+10, p1-7)

array([22, 24,  0, 72, 42, 38, 38, 14, 10])

In [69]:
w1 = np.array([[1,2,7],[3,4,-8],[5,6,0]])
w1

array([[ 1,  2,  7],
       [ 3,  4, -8],
       [ 5,  6,  0]])

In [70]:
np.where(w1%2==0)

(array([0, 1, 1, 2, 2], dtype=int64), array([1, 1, 2, 1, 2], dtype=int64))

In [71]:
w1[np.where(w1%2==0)]

array([ 2,  4, -8,  6,  0])

#### f) np.extract() - directly returns the values on which conditions are applied,using the second parameter as array name

In [72]:
p1

array([12, 14,  7, 79, 32, 45, 28,  4, 17])

In [74]:
t1 = np.extract(p1>20, p1)
print(t1)
type(t1)

[79 32 45 28]


numpy.ndarray

In [75]:
p1

array([12, 14,  7, 79, 32, 45, 28,  4, 17])

In [78]:
np.extract(p1%3!=0,p1)

array([14,  7, 79, 32, 28,  4, 17])

In [80]:
w1 = np.array([[1,2,7],[3,4,8],[5,6,13]])
w1

array([[ 1,  2,  7],
       [ 3,  4,  8],
       [ 5,  6, 13]])

In [81]:
w2 = np.extract(w1%3!=0,w1)
print(w2)

[ 1  2  7  4  8  5 13]


#### g) np.insert() - adds values at specified position

In [84]:
p1

array([12, 14,  7, 79, 32, 45, 28,  4, 17])

In [87]:
np.insert(p1,2,41)

array([12, 14, 41,  7, 79, 32, 45, 28,  4, 17])

In [88]:
p1

array([12, 14,  7, 79, 32, 45, 28,  4, 17])

In [90]:
np.insert(p1,7,56)

array([12, 14,  7, 79, 32, 45, 28, 56,  4, 17])

In [92]:
# Working on 2D array  
arr = np.arange(12).reshape(3, 4) 
print("2D arr : \n", arr) 
print("Shape : ", arr.shape) 
  
a = np.insert(arr, 1, 9, axis = 1) 
# row wise insertion of 9 theryby creating a new column
print("Array after insertion :\n", a) 
print("Shape : ", a.shape) 

b = np.insert(arr, 2, 41, axis = 0)  
# column wise insertion of 41 theryby creating a new column
print("Array after insertion :\n", b) 
print("Shape : ", b.shape) 

2D arr : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape :  (3, 4)
Array after insertion :
 [[ 0  9  1  2  3]
 [ 4  9  5  6  7]
 [ 8  9  9 10 11]]
Shape :  (3, 5)
Array after insertion :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [41 41 41 41]
 [ 8  9 10 11]]
Shape :  (4, 4)


#### h) np.delete() - deletes values at specified position/index

In [93]:
p1

array([12, 14,  7, 79, 32, 45, 28,  4, 17])

In [94]:
p2 = np.delete(p1,4)
p2

array([12, 14,  7, 79, 45, 28,  4, 17])

In [95]:
p1

array([12, 14,  7, 79, 32, 45, 28,  4, 17])

In [96]:
w1

array([[ 1,  2,  7],
       [ 3,  4,  8],
       [ 5,  6, 13]])

In [97]:
q1 = np.delete(w1,2,axis=1)  # deletes 2nd index column value corresponding to each row
print(q1)

[[1 2]
 [3 4]
 [5 6]]


In [98]:
w1

array([[ 1,  2,  7],
       [ 3,  4,  8],
       [ 5,  6, 13]])

In [100]:
q1 = np.delete(w1,2,axis=0) # deletes 2nd index row value corresponding to each column
print(q1)

[[1 2 7]
 [3 4 8]]


## 3) Appending values ino array 

In [102]:
a1 = np.array([12, 14,  7, 79, 32, 45, 28,  4, 17])
a1

array([12, 14,  7, 79, 32, 45, 28,  4, 17])

In [103]:
np.append(a1,23)

array([12, 14,  7, 79, 32, 45, 28,  4, 17, 23])

In [104]:
print(a1)

[12 14  7 79 32 45 28  4 17]


In [106]:
np.append(a1,36)

array([12, 14,  7, 79, 32, 45, 28,  4, 17, 36])

In [107]:
w1 = np.array([[1,2,7],[3,4,8],[5,6,13]])
print(w1)
print(w1.shape)

[[ 1  2  7]
 [ 3  4  8]
 [ 5  6 13]]
(3, 3)


In [108]:
w2 = np.append(w1,45)
print(w2)

[ 1  2  7  3  4  8  5  6 13 45]


In [109]:
r1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape(3,4)
r1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### a) Append/Add a new Row/Column

In [110]:
print(r1)
print(r1.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [118]:
# Column wise - Add a value to each column, thereby creaing a new row
r2 = np.append(r1, [[13,14,15,16]], axis=0) 
print(r1)
print(r1.shape)
print('-------')
print(r2)
print(r2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
-------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
(4, 4)


In [119]:
print(r1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [125]:
# Row wise - Add a value to each row, thereby creaing a new column
r4 = np.append(r1, [[500],[600],[700]], axis=1)
print(r1)
print(r1.shape)
print('-------')
print(r4)
print(r4.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
-------
[[  1   2   3   4 500]
 [  5   6   7   8 600]
 [  9  10  11  12 700]]
(3, 5)


In [126]:
print(r1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### 4) Iterating over numpy array - np.nditer()

In [127]:
p1 = np.array([12, 14,  7, 79, 32, 45, 28,  4, 17])
print(p1)
type(p1)

[12 14  7 79 32 45 28  4 17]


numpy.ndarray

In [128]:
for i in p1:
    print(i)

12
14
7
79
32
45
28
4
17


In [129]:
for i in np.nditer(p1):
    print(i)

12
14
7
79
32
45
28
4
17


In [131]:
n1 = np.arange(2,70,8).reshape(3,3)
print(n1)

[[ 2 10 18]
 [26 34 42]
 [50 58 66]]


In [134]:
for i in n1:
    print(i)

[ 2 10 18]
[26 34 42]
[50 58 66]


In [136]:
for i in np.nditer(n1):
    print(i)

2
10
18
26
34
42
50
58
66


In [138]:
n1

array([[ 2, 10, 18],
       [26, 34, 42],
       [50, 58, 66]])

In [139]:
n1.flatten()

array([ 2, 10, 18, 26, 34, 42, 50, 58, 66])

In [144]:
for i in n1.flatten():
    print(i)

2
10
18
26
34
42
50
58
66


In [145]:
n1

array([[ 2, 10, 18],
       [26, 34, 42],
       [50, 58, 66]])

In [147]:
for i in n1:
    print(i)

[ 2 10 18]
[26 34 42]
[50 58 66]


In [146]:
for i in np.nditer(n1):  
    print(i,end=' ')

2 10 18 26 34 42 50 58 66 

In [148]:
for i in np.nditer(n1,order='C'):  # order= 'C', iterates element row wise
    print(i,end=' ')

2 10 18 26 34 42 50 58 66 

In [149]:
n1

array([[ 2, 10, 18],
       [26, 34, 42],
       [50, 58, 66]])

In [155]:
for i in np.nditer(n1,order='F'):  # order= 'F', print element column wise
    print(i,end=' ')

2 26 50 10 34 58 18 42 66 

In [152]:
n1

array([[ 2, 10, 18],
       [26, 34, 42],
       [50, 58, 66]])

In [153]:
for i in np.nditer(n1,order='A'):  # order= 'A', print element row wise
    print(i,end=' ')

2 10 18 26 34 42 50 58 66 

In [154]:
for i in np.nditer(n1,order='K'):  # order= 'K', print element row wise
    print(i,end=' ')

2 10 18 26 34 42 50 58 66 

In [159]:
n1

array([[ 2, 10, 18],
       [26, 34, 42],
       [50, 58, 66]])

In [162]:
n2 = np.arange(100,109).reshape(3,3)
n2

array([[100, 101, 102],
       [103, 104, 105],
       [106, 107, 108]])

In [163]:
for x,y in np.nditer([n1,n2]): 
    print(x,y)

2 100
10 101
18 102
26 103
34 104
42 105
50 106
58 107
66 108


## 5) Matrix Multiplication and Transpose, Flatten

In [165]:
r1 = np.arange(2,20,2).reshape(3,3)
print(r1)  # Normal matrix

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [167]:
print(r1.T)            # Transpose of the array
print(np.transpose(r1))            # Transpose of the array
print(r1.flatten())    # Flatten the normal array
print(r1.T.flatten())  # Flattenthe transpose of the array

[[ 2  8 14]
 [ 4 10 16]
 [ 6 12 18]]
[[ 2  8 14]
 [ 4 10 16]
 [ 6 12 18]]
[ 2  4  6  8 10 12 14 16 18]
[ 2  8 14  4 10 16  6 12 18]


In [169]:
a1 = np.array([8,5,0,2,9,6,4,1,7]).reshape(3,3)
a2 = np.array([3,7,9,4,1,0,5,6,2]).reshape(3,3)
print(a1)
print(a2)

[[8 5 0]
 [2 9 6]
 [4 1 7]]
[[3 7 9]
 [4 1 0]
 [5 6 2]]


In [170]:
# Actual Matrix multiplication
r2 = np.matmul(a1,a2)
print(r2)

[[44 61 72]
 [72 59 30]
 [51 71 50]]


In [172]:
# Actual Matrix multiplication
r2 = np.dot(a1,a2)
print(r2)

[[44 61 72]
 [72 59 30]
 [51 71 50]]


In [173]:
print(a1)
print(a2)

[[8 5 0]
 [2 9 6]
 [4 1 7]]
[[3 7 9]
 [4 1 0]
 [5 6 2]]


In [174]:
# Element wise multiplication
r3 = np.multiply(a1,a2)
print(r3)

[[24 35  0]
 [ 8  9  0]
 [20  6 14]]


<b>Linear algebra in NumPy:</b> 
<br>The Linear Algebra module of NumPy offers various methods to apply linear algebra 
on any numpy array. It can be used to determine:
<ol>
<li>rank, determinant, trace, etc. of an array.</li>
<li>solve linear equations</li>
</ol>

In [175]:
A = np.array([[0,1,2], 
              [2,3,4], 
              [1,2,5]],dtype=int) 
print(A)

[[0 1 2]
 [2 3 4]
 [1 2 5]]


In [181]:
print("Rank of A:", np.linalg.matrix_rank(A)) 
  
print("Trace of A:", np.trace(A))  # 0+3+5 = sum of primary diagonal
  
print("Determinant of A:", np.linalg.det(A)) 
# 0(3*5-4*2) - 1(2*5 - 4*1) + 2(2*2 - 3*1)  = -6 + 2(1) = -6 + 2 = -4
  
print("Inverse of A:\n", np.linalg.inv(A)) 

Rank of A: 3
Trace of A: 8
Determinant of A: -4.0
Inverse of A:
 [[-1.75  0.25  0.5 ]
 [ 1.5   0.5  -1.  ]
 [-0.25 -0.25  0.5 ]]


### Solving Linear Equations using numpy

In [182]:
# Solving the equation:-
# x - 2y = 8
# 3x + 4y = 18

a = np.array([[1, -2], [3, 4]]) 
b = np.array([8, 18]) 
  
print("Solution of linear equations:", np.linalg.solve(a, b))

Solution of linear equations: [ 6.8 -0.6]


In [183]:
# Solving the equation:-
# x +2y-z = 9
# 2x -3y+7z = 15
# 7x -4y-5z = 13

a = np.array([[1, 2, -1], [2, -3, 7], [7, -4, -5]],dtype=int)
b = np.array([9,15,13],dtype=int)
x = np.linalg.solve(a, b)
print(x)

[5. 3. 2.]


In [184]:
s1 = np.array([[0,1,2],[2,3,4],[0,2,1]])
print(s1)
print("Determinant of A:", np.linalg.det(s1)) 

[[0 1 2]
 [2 3 4]
 [0 2 1]]
Determinant of A: 6.0
