In [1]:
import numpy as np

## Numpy array functions

In [144]:
r1 = [[12,13,4],[15,17,16],[18,19,11],[16,22,20]]
a1 = np.array(r1)
print(a1)

[[12 13  4]
 [15 17 16]
 [18 19 11]
 [16 22 20]]


### a) np.sum()

In [145]:
print(a1)

[[12 13  4]
 [15 17 16]
 [18 19 11]
 [16 22 20]]


In [146]:
a1.sum()

183

In [147]:
print(a1)

[[12 13  4]
 [15 17 16]
 [18 19 11]
 [16 22 20]]


In [148]:
# Row wise addition, axis=1
print(a1.sum(axis=1))
# Column wise addition, axis=0
print(a1.sum(axis=0))

[29 48 48 58]
[61 71 51]


### b) np.max() and np.min()

In [149]:
print(a1)

[[12 13  4]
 [15 17 16]
 [18 19 11]
 [16 22 20]]


In [150]:
print(np.max(a1))
print(np.min(a1))
print(a1)

22
4
[[12 13  4]
 [15 17 16]
 [18 19 11]
 [16 22 20]]


In [151]:
# axis=1 => Rows
# axis=0 => Columns
print(np.max(a1,axis=0))
print(np.max(a1,axis=1))
print(np.min(a1,axis=0))
print(np.min(a1,axis=1))

[18 22 20]
[13 17 19 22]
[12 13  4]
[ 4 15 11 16]


### c) np.argmax() and np.argmin()
<b>np.argmax()</b> - Returns the indices of the maximum values along an axis <br>  
<b>np.argmin() </b>- Returns the indices of the minimum values along an axis 

In [152]:
p1 = np.array([12,14,7,79,32,45,28,4,17])
print(p1)

[12 14  7 79 32 45 28  4 17]


In [153]:
print(np.max(p1))
print(np.min(p1))

79
4


In [154]:
print(np.argmax(p1))
print(np.argmin(p1))

3
7


In [155]:
max_value = p1[np.argmax(p1)]
min_value = p1[np.argmin(p1)]
print('Max_value is ',max_value)
print('Min_value is ',min_value)

Max_value is  79
Min_value is  4


In [156]:
r2 = [[16,15,21],[15,16,8],[19,2,18],[9,12,13]]
p2 = np.array(r2)
print(p2)

[[16 15 21]
 [15 16  8]
 [19  2 18]
 [ 9 12 13]]


In [157]:
print(np.argmax(p2,axis=0))  # column wise
print(np.argmin(p2,axis=0))  # column wise
print(np.argmax(p2,axis=1))  # row wise
print(np.argmin(p2,axis=1))  # row wise

[2 1 0]
[3 2 1]
[2 1 0 2]
[1 2 1 0]


### d) np.sort

In [158]:
r1 = np.array([34,23,56,12,39])
print(r1)          

[34 23 56 12 39]


In [159]:
np.sort(r1)
print(r1)         

[34 23 56 12 39]


In [160]:
r2 = np.sort(r1) # ascending order
print(r2)
r2 = np.sort(r1)[::-1] # descending order
print(r2)

[12 23 34 39 56]
[56 39 34 23 12]


In [161]:
r3 = np.array([[11,21,18],[24,35,16],[7,14,3]])
print(r3)

[[11 21 18]
 [24 35 16]
 [ 7 14  3]]


In [162]:
# sorts row wise
r4 = np.sort(r3,axis=1)
print(r4)
# sorts column wise
r5 = np.sort(r3,axis=0)
print(r5)

[[11 18 21]
 [16 24 35]
 [ 3  7 14]]
[[ 7 14  3]
 [11 21 16]
 [24 35 18]]


### e) np.where() - returns index position for the matching conditions

In [163]:
p1 = np.array([12,14,7,79,32,45,28,4,17])
print(p1)

[12 14  7 79 32 45 28  4 17]


In [164]:
n2 = np.where(p1%3==0)
print(n2)
print(p1[np.where(p1%3==0)])

(array([0, 5], dtype=int64),)
[12 45]


In [165]:
print(p1)
print(np.where(p1 < 20))
print(p1[np.where(p1 < 20)])

[12 14  7 79 32 45 28  4 17]
(array([0, 1, 2, 7, 8], dtype=int64),)
[12 14  7  4 17]


In [166]:
print(p1)
t1 = np.where(p1 < 20, p1+5, p1*2)
print(t1)
t2 = np.where(p1%2==0, p1+10, p1-7)
print(t2)

[12 14  7 79 32 45 28  4 17]
[ 17  19  12 158  64  90  56   9  22]
[22 24  0 72 42 38 38 14 10]


In [167]:
w1 = np.array([[1,2,7],[3,4,-8],[5,6,0]])
print(w1)

[[ 1  2  7]
 [ 3  4 -8]
 [ 5  6  0]]


In [168]:
print(np.where(w1%2==0))
print(w1[np.where(w1%2==0)])

(array([0, 1, 1, 2, 2], dtype=int64), array([1, 1, 2, 1, 2], dtype=int64))
[ 2  4 -8  6  0]


### f) np.extract() - 
Directly returns the values on which conditions are applied,using the second parameter as array name

In [169]:
print(p1)
t1 = np.extract(p1>20, p1)
print(t1)
t2 = np.extract(p1%3!=0,p1)
print(t2)

[12 14  7 79 32 45 28  4 17]
[79 32 45 28]
[14  7 79 32 28  4 17]


In [170]:
w1 = np.array([[1,2,7],[3,4,8],[5,6,13]])
print(w1)

[[ 1  2  7]
 [ 3  4  8]
 [ 5  6 13]]


In [171]:
w2 = np.extract(w1%3!=0,w1)
print(w2)

[ 1  2  7  4  8  5 13]


### g) np.concatenate()
Join a sequence of arrays along an existing axis.

In [172]:
w1 = np.array([12,13,14,15])
w2 = np.array([18,19,20,21,22])

r1 = np.concatenate([w1,w2])
print(r1)

[12 13 14 15 18 19 20 21 22]


In [173]:
d1 = np.array([[1,2,3],[4,5,6]])
d2 = np.array([[7,8,9],[10,11,13]])
print(d1)
print(d2)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 13]]


In [174]:
r2 = np.concatenate([d1,d2],axis=0)
print(r2)
r3 = np.concatenate([d1,d2],axis=1)
print(r3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 13]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 13]]


### Iterating over numpy array - np.nditer()

In [175]:
p1 = np.array([12, 14,  7, 79, 32, 45])
print(p1)
type(p1)

[12 14  7 79 32 45]


numpy.ndarray

In [176]:
for i in p1:
    print(i)

12
14
7
79
32
45


In [177]:
for i in np.nditer(p1):
    print(i)

12
14
7
79
32
45


In [178]:
n1 = np.arange(2,70,8).reshape(3,3)
print(n1)

[[ 2 10 18]
 [26 34 42]
 [50 58 66]]


In [179]:
for i in n1:
    print(i)

[ 2 10 18]
[26 34 42]
[50 58 66]


In [180]:
for i in np.nditer(n1):
    print(i,end=' ')

2 10 18 26 34 42 50 58 66 

In [181]:
print(n1)

[[ 2 10 18]
 [26 34 42]
 [50 58 66]]


In [182]:
for i in np.nditer(n1):  
    print(i,end=' ')

2 10 18 26 34 42 50 58 66 

In [183]:
for i in np.nditer(n1,order='C'):  # order= 'C', iterates element row wise
    print(i,end=' ')

2 10 18 26 34 42 50 58 66 

In [184]:
for i in np.nditer(n1,order='F'):  # order= 'F', print element column wise
    print(i,end=' ')

2 26 50 10 34 58 18 42 66 

In [185]:
n2 = np.arange(100,109).reshape(3,3)
print(n2)

[[100 101 102]
 [103 104 105]
 [106 107 108]]


In [186]:
for x,y in np.nditer([n1,n2]): 
    print(x,y)

2 100
10 101
18 102
26 103
34 104
42 105
50 106
58 107
66 108


## Matrix related Operations  - Multiply, Transpose, Flatten

In [187]:
r1 = np.arange(2,20,2).reshape(3,3)
print(r1)  

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [192]:
print(r1.T)             # Transpose of the array
print(r1.transpose())   # Transpose of the array
print(np.transpose(r1)) # Transpose of the array
print(r1.flatten())     # Flatten the normal array
print(r1.T.flatten())   # Flattenthe transpose of the array

[[ 2  8 14]
 [ 4 10 16]
 [ 6 12 18]]
[[ 2  8 14]
 [ 4 10 16]
 [ 6 12 18]]
[[ 2  8 14]
 [ 4 10 16]
 [ 6 12 18]]
[ 2  4  6  8 10 12 14 16 18]
[ 2  8 14  4 10 16  6 12 18]


In [189]:
a1 = np.array([8,5,0,2,9,6,4,1,7]).reshape(3,3)
a2 = np.array([3,7,9,4,1,0,5,6,2]).reshape(3,3)
print(a1)
print(a2)

[[8 5 0]
 [2 9 6]
 [4 1 7]]
[[3 7 9]
 [4 1 0]
 [5 6 2]]


### Matrix Multiplication

In [137]:
# Actual Matrix multiplication
r2 = np.matmul(a1,a2)
print(r2)

[[44 61 72]
 [72 59 30]
 [51 71 50]]


In [138]:
# Actual Matrix multiplication
r2 = np.dot(a1,a2)
print(r2)

[[44 61 72]
 [72 59 30]
 [51 71 50]]


In [139]:
print(a1)
print(a2)

[[8 5 0]
 [2 9 6]
 [4 1 7]]
[[3 7 9]
 [4 1 0]
 [5 6 2]]


In [140]:
# Element wise multiplication
r3 = np.multiply(a1,a2)
print(r3)

[[24 35  0]
 [ 8  9  0]
 [20  6 14]]
