#### Numpy (Numerical Python)

1) NumPy is the fundamental package for scientific computing in Python<br>
2) It is used for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, basic linear algebra, basic statistical operations and much more.<br>
3) The NumPy library contains multidimensional array and matrix data structures<br>
4) It provides ndarray, a homogeneous n-dimensional array object, with wide variety of methods to efficiently operate on it.

#### Numpy Array
1) An array is a central data structure of the NumPy library.<br>

2) An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the array dtype.

#### Difference between list and Numpy arrays

#### List
1) It is an ordered collection of elements of same or different data types


#### Numpy Array
1) It is an ordered collection of elements of same data type. Elements in numpy array are homogeneous.<br>
2) Numpy arrays are faster than list<br>

### Creating Numpy Arrays
1) np.array()<br>
2) np.arange()

Other methods<br>

3) np.zeros()<br>
4) np.ones()<br>
5) np.linspace()<br>

In [21]:
import numpy as np

### 1) np.array()
1) The data type of the numpy array is <b>np.ndarray</b><br>
2) An array is usually a fixed-size container of items of the same type and size. The number of dimensions and items in an array is defined by its shape 
    

In [22]:
n1 = np.array([5,7,8,3,7])
print(n1)
print(type(n1))

[5 7 8 3 7]
<class 'numpy.ndarray'>


In [23]:
# Creating numpy arrays using List and tuple
a1 = [10,20,30,40]
a2 = (5,7,3,8)
w1 = np.array(a1)
w2 = np.array(a2)
print(w1)
print(w2)

[10 20 30 40]
[5 7 3 8]


#### Attributes of numpy array

1) dtype - Returns data type of ndarray<br>
2) size - Returns size(number of elements) of ndarray<br>
3) shape - Returns shape(in terms of rows and columns,starting from 2 dimensions) of ndarray<br>
4) ndim - Returns number of dimensions of ndarray<br>

In [13]:
s1 = np.array([7,8,6,5,4,3,5,6,7,8])
print(s1)
print(s1.dtype)
print(s1.size)
print(s1.shape)
print(s1.ndim)

[7 8 6 5 4 3 5 6 7 8]
int32
10
(10,)
1


In [17]:
s2 = np.array([[5,10,15],[20,30,354]])
print(s2)
print(s2.dtype)
print(s2.size)
print(s2.shape)
print(s2.ndim)

[[  5  10  15]
 [ 20  30 354]]
int32
6
(2, 3)
2


In [19]:
s3 = np.array([[[5,10,15],[20,30,354]],[[1,2,3],[4,5,6]]])
print(s3)
print(s3.dtype)
print(s3.size)
print(s3.shape)
print(s3.ndim)

[[[  5  10  15]
  [ 20  30 354]]

 [[  1   2   3]
  [  4   5   6]]]
int32
12
(2, 2, 3)
3


In [24]:
s0 = np.array(67)
print(s0)
print(s0.dtype)
print(s0.size)
print(s0.shape)
print(s0.ndim)

67
int32
1
()
0


### 2) np.arange()



In [25]:
w1 = np.arange(10,20)
print(w1)

[10 11 12 13 14 15 16 17 18 19]


In [28]:
w2 = np.arange(5,25,4)
print(w2)
w3 = np.arange(30,10,-5)
print(w3)

[ 5  9 13 17 21]
[30 25 20 15]


### 3) np.linspace()
Generates linearly spaced elements

In [33]:
z1 = np.linspace(2,10,5)
print(z1)
z2 = np.linspace(2,10,3)
print(z2)

[ 2.  4.  6.  8. 10.]
[ 2.  6. 10.]


In [35]:
z3 = np.linspace(4,17,6)
print(z3)

[ 4.   6.6  9.2 11.8 14.4 17. ]


In [36]:
z4 = np.linspace(2,20)
print(z4)

[ 2.          2.36734694  2.73469388  3.10204082  3.46938776  3.83673469
  4.20408163  4.57142857  4.93877551  5.30612245  5.67346939  6.04081633
  6.40816327  6.7755102   7.14285714  7.51020408  7.87755102  8.24489796
  8.6122449   8.97959184  9.34693878  9.71428571 10.08163265 10.44897959
 10.81632653 11.18367347 11.55102041 11.91836735 12.28571429 12.65306122
 13.02040816 13.3877551  13.75510204 14.12244898 14.48979592 14.85714286
 15.2244898  15.59183673 15.95918367 16.32653061 16.69387755 17.06122449
 17.42857143 17.79591837 18.16326531 18.53061224 18.89795918 19.26530612
 19.63265306 20.        ]


#### np.zeros() - Generates an array of zeros
#### np.ones() - Generates an array of ones

In [38]:
d1 = np.zeros((3,4))
print(d1)
d2 = np.ones((4,5),dtype=int)
print(d2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


#### Reshape and shape()

In [52]:
b1 = np.array([3,4,5,6,7,8,9,10,11,12,13,14])
print(b1)
print(b1.shape)
b2 = np.array([3,4,5,6,7,8,9,10,11,12,13,14]).reshape(3,4)
print(b2)
print(b2.shape)

[ 3  4  5  6  7  8  9 10 11 12 13 14]
(12,)
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
(3, 4)


In [62]:
b3 = b2.reshape(2,6)
print(b3)
print(b3.shape)

[[ 3  4  5  6  7  8]
 [ 9 10 11 12 13 14]]
(2, 6)


In [61]:
print(b2.shape)

(3, 4)


In [68]:
b4 = np.arange(1,19).reshape(6,3)
print(b4)
print(b4.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
(6, 3)


In [69]:
b4.reshape(2,3,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [70]:
print(b4.shape)

(6, 3)


In [72]:
b4.shape = (3,2,3)
print(b4)
print(b4.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
(3, 2, 3)


### Numpy random numbers

#### 1) np.random.random()
Return random floats in the half-open interval [0.0, 1.0).

In [83]:
a1 = np.random.random(5)
print(a1)
a2 = np.random.random((3,2))
print(a2)

[0.24003303 0.25996895 0.13247389 0.6623688  0.6135923 ]
[[0.59153978 0.50417739]
 [0.54670587 0.60547557]
 [0.30244471 0.93895771]]


#### 2) np.random.randint(low,high,size)
Return random integers from `low` (inclusive) to `high` (exclusive).

In [85]:
a3 = np.random.randint(3,20,7)
print(a3)
a4 = np.random.randint(50,100,8)
print(a4)

[18  8 11  9 15 13  3]
[86 85 56 88 81 57 56 98]


#### 3) np.random.rand()
generates random values between [0, 1) in the given shape.

In [87]:
w1 = np.random.rand(5)
print(w1)
w2 = np.random.rand(4,2)
print(w2)

[0.69883846 0.48965443 0.99961294 0.3683419  0.85760098]
[[0.7918532  0.78781533]
 [0.27768179 0.23105112]
 [0.84470204 0.18873977]
 [0.48961043 0.49905359]]


#### 4) np.random.random_sample()
Returns random floats between [0,1)

In [89]:
r1 = np.random.random_sample(6)
print(r1)
r2 = np.random.random_sample((4,3))
print(r2)

[0.29513393 0.11737928 0.21842797 0.16509819 0.5264627  0.45747108]
[[0.94688127 0.89856131 0.06449863]
 [0.31699621 0.04239464 0.90952693]
 [0.09690178 0.300504   0.7288259 ]
 [0.51816836 0.315571   0.90547265]]
